### ISSUE TITLE
Potential Snapshot outage

### ISSUE THREAD

**Issue by malvonme** [oceanprotocol/oceandao#546] opened 2022-07-11 19:28 UTC
**Situation:**
Currently, voting and voted wallets are not loading in our Round 19 Snapshot:
https://snapshot.org/#/officialoceandao.eth/proposal/bafkreifsu3bxqjngyhcbehz6vokvniuh4d476j2ga4t4z6x6duosfjknqu

**Goal & DoD:**
- [ ] Snapshot is fully up and running
- [ ] Voting works

**Comment:**
T-4.5h till deadline

**Comment by malvonme** [comment] 2022-07-11 19:45
I remember last time there was a problem with our host? Maybe this again? Happy for help. Thx!

**Comment by idiom-bytes** [comment] 2022-07-11 19:45
The last time the problem was with our subgraph.
I'm trying to see if I can reproduce it there and see which one is down.

I just tested gitcoin and they have a live ballot that is working.
https://snapshot.org/#/gitcoindao.eth/proposal/0x7827fdf2b3aa1569e3e9a078af1f1171682f649f2b12327f69b822dc37e0ae25

I can reproduce the issue. (img below)
![Screenshot from 2022-07-11 12-45-06](https://user-images.githubusercontent.com/69865342/178345927-3b29b753-56e1-44a2-83ad-ca7eb64f353c.png)

**Comment by idiom-bytes** [comment] 2022-07-13 14:26
This was addressed, moving to closed.

**Closed as completed by idiom-bytes** 2022-07-13 14:26 UTC
Labels: Type: Bug, Priority: Critical, Status: Blocked
